import type { Metadata } from "next"
import "@/styles/globals.css"
import { Inter } from "next/font/google"

export const metadata: Metadata = {
  title: "XScouting",
  description: "Generated by create next app",
}

const inter = Inter({
  subsets: ['latin'],
})

import { Analytics } from "@vercel/analytics/next"
import { SpeedInsights } from '@vercel/speed-insights/next'

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className={inter.className}>
      <body>
        {children}
        <Analytics />
        <SpeedInsights />
      </body>
    </html>
  )
}
