import type { Metadata } from "next";
import "@/styles/globals.css";

export const metadata: Metadata = {
  title: "XScouting",
  description: "Generated by create next app",
};

import { Analytics } from "@vercel/analytics/next"
import { SpeedInsights } from '@vercel/speed-insights/next'

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
        <Analytics />
        <SpeedInsights />
      </body>
    </html>
  );
}
